### ISSUE TITLE
Deployment fails at applying transforms step

### ISSUE THREAD

**Issue by schnitty** [Sitecore/Sitecore.HabitatHome.Content#26]
**Describe the bug**

**To Reproduce**
clone repo
npm install
.\node_modules\.bin\gulp

Get error:

```
  Sitecore.HabitatHome.Habitat.Website -> C:\Projects\Sitecore.HabitatHome.Content\src\Project\Habitat\code\bin\Sitecore.HabitatHome.Global.Website.dll
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
  Sitecore.HabitatHome.Common.Website -> C:\Projects\Sitecore.HabitatHome.Content\src\Project\Common\code\bin\Sitecore.HabitatHome.Common.Website.dll
  Sitecore.HabitatHome.Website -> C:\Projects\Sitecore.HabitatHome.Content\src\Project\HabitatHome\code\bin\Sitecore.HabitatHome.Website.dll
  Copying all files to temporary location below for package/publish:
  Copying all files to temporary location below for package/publish:
  obj\Debug\Package\PackageTmp.
  obj\Debug\Package\PackageTmp.
[18:43:09] Applying configuration transform: C:\Projects\Sitecore.HabitatHome.Content\src\Foundation\Accounts\code\App_Config\Security\domains.config.xdt
[18:43:11] MSBuild complete!
[18:43:11] MSBuild complete!
[18:43:11] Applying configuration transform: C:\Projects\Sitecore.HabitatHome.Content\src\Feature\CRM\code\web.config.xdt
[18:43:11] MSBuild complete!
[18:43:11] MSBuild complete!
C:\Projects\Sitecore.HabitatHome.Content\scripts\applytransform.targets(14,5): error : Could not open Source file: Could not find file 'C:\inetpub\wwwroot\habitat.dev.local\web.config'.
[18:43:11] MSBuild failed with code 1!
error!
[18:43:11] 'Apply-Xml-Transform' errored after 3.54 s
[18:43:11] Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\Projects\Sitecore.HabitatHome.Content\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[18:43:11] 'default' errored after 1.58 min
[18:43:11] Error in plugin 'run-sequence(Apply-Xml-Transform)'
Message:
    MSBuild failed with code 1!
Stack:
Error: MSBuild failed with code 1!
    at ChildProcess.<anonymous> (C:\Projects\Sitecore.HabitatHome.Content\node_modules\gulp-msbuild\lib\msbuild-runner.js:66:25)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

C:\Projects\Sitecore.HabitatHome.Content (develop -> origin) (habitat@9.0.0)
```

**Expected behavior**
Completes all tasks in gulp scripts and have a working site

**Comment by jeanfrancoislarente** [comment]
Hey @schnitty , can you provide details on your publishsettings.targets, your gulp-config.js and your IIS Settings (screenshot of the latter is fine).

Did you have a working XPSingle site before you tried to deploy?

**Comment by jeanfrancoislarente** [comment]
`C:\Projects\Sitecore.HabitatHome.Content\scripts\applytransform.targets(14,5): error : Could not open Source file: Could not find file 'C:\inetpub\wwwroot\habitat.dev.local\web.config'.`

Looks like it can't find the web.config - either one of your configs is incorrect or there is something wrong with your base Sitecore XP installation.

Is this still an issue @schnitty?

**Comment by edrichtt** [comment]
Hi @schnitty ,

I had the same issue and it turns out that the default Habitat Home Platform host name (habitathome.dev.local) didn't point to where my vanilla XP install was (sc910.sc).

Make sure you Habitat Home Platform hostname aligns with your vanilla XP install host name.
